<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastArticles($offset = 0, $limit = 2){
        return $this->findBy(array(), array("id" => "DESC"),$limit,$offset);
    }
}
